ingrediente/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # lista todos os ingredientes
    path('ingredientes/', views.listar_ingredientes, name='listar_ingredientes'),

    # acompanhamentos
    path('acompanhamentos/adicionar/', views.adicionar_acompanhamento, name='adicionar_acompanhamento'),
    path('acompanhamentos/editar/<int:acompanhamento_id>/', views.editar_acompanhamento, name='editar_acompanhamento'),
    path('acompanhamentos/remover/<int:acompanhamento_id>/', views.remover_acompanhamento, name='remover_acompanhamento'),

    # sabores
    path('sabores/adicionar/', views.adicionar_sabor, name='adicionar_sabor'),
    path('sabores/editar/<int:sabor_id>/', views.editar_sabor, name='editar_sabor'),
    path('sabores/remover/<int:sabor_id>/', views.remover_sabor, name='remover_sabor'),

    # tamanhos
    path('tamanhos/adicionar/', views.adicionar_tamanho, name='adicionar_tamanho'),
    path('tamanhos/editar/<int:tamanho_id>/', views.editar_tamanho, name='editar_tamanho'),
    path('tamanhos/remover/<int:tamanho_id>/', views.remover_tamanho, name='remover_tamanho'),
]

pedido/urls.py
from django.urls import path
from . import views

urlpatterns = [

    path('', views.listar_index, name='listar_index'),
    path('fazer-pedido/<int:produto_id>/', views.fazer_pedido, name='fazer_pedido'),
    path('resumo-pedido/<int:pedido_id>/', views.resumo_pedido, name='resumo_pedido'),

    path('fazer-pedido-personalizado/', views.fazer_pedido_personalizado, name='fazer_pedido_personalizado'),
    path('resumo-pedido-personalizado/<int:pedido_id>/', views.resumo_pedido_personalizado, name='resumo_pedido_personalizado'),

    path('meus-pedidos/', views.meus_pedidos, name='meus_pedidos'),
    path('listar-pedidos/', views.listar_pedidos, name='listar_pedidos'),
    path('pedido-confirmado/<int:pedido_id>/<str:tipo_pedido>/', views.pedido_confirmado, name='pedido_confirmado'),
    path('atualizar-status/<int:pedido_id>/<str:tipo_pedido>/', views.atualizar_status, name='atualizar_status'),

]

projetofinal/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuario/', include('usuario.urls')),
    path('produto/', include('produto.urls')),
    path('ingrediente/', include('ingrediente.urls')),
    path('', include('pedido.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ingrediente/models.py
from django.db import models

class Sabor(models.Model):
    nome = models.CharField(max_length=100)
    preco_adicional = models.DecimalField(max_digits=5, decimal_places=2)

    def __str__(self):
        return f"{self.nome} (+R$ {self.preco_adicional})"


class Acompanhamento(models.Model):
    nome = models.CharField(max_length=100)
    preco_adicional = models.DecimalField(max_digits=5, decimal_places=2)

    def __str__(self):
        return f"{self.nome} (+R$ {self.preco_adicional})"


class Tamanho(models.Model):
    nome = models.CharField(max_length=50)  
    preco_adicional = models.DecimalField(max_digits=5, decimal_places=2)

    def __str__(self):
        return f"{self.nome} (+R$ {self.preco_adicional})"

ingrediente/forms.py
from django import forms
from .models import Acompanhamento, Sabor, Tamanho

class AcompanhamentoForm(forms.ModelForm):
    class Meta:
        model = Acompanhamento  # Alterado para Acompanhamento
        fields = ['nome', 'preco_adicional']

class SaborForm(forms.ModelForm):
    class Meta:
        model = Sabor
        fields = ['nome', 'preco_adicional']

class TamanhoForm(forms.ModelForm):
    class Meta:
        model = Tamanho
        fields = ['nome', 'preco_adicional']
    
    def __init__(self, *args, **kwargs):
        super(TamanhoForm, self).__init__(*args, **kwargs)
        self.fields['nome'].widget.attrs.update({'class': 'form-control'})
        self.fields['preco_adicional'].widget.attrs.update({'class': 'form-control'})

ingrediente/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Acompanhamento, Tamanho, Sabor
from .forms import AcompanhamentoForm, TamanhoForm, SaborForm

# ------------- lista todos os ingredientes -------------
def listar_ingredientes(request):
    acompanhamentos = Acompanhamento.objects.all()
    tamanhos = Tamanho.objects.all()
    sabores = Sabor.objects.all()
    return render(request, 'ingrediente/listar_ingredientes.html', {'acompanhamentos': acompanhamentos, 'tamanhos': tamanhos, 'sabores': sabores})

# ------------- Acompanhamentos -------------
def adicionar_acompanhamento(request):
    if request.method == 'POST':
        form = AcompanhamentoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('listar_ingredientes')
    else:
        form = AcompanhamentoForm()
    return render(request, 'ingrediente/adicionar_acompanhamento.html', {'form': form})

def editar_acompanhamento(request, acompanhamento_id):
    acompanhamento = get_object_or_404(Acompanhamento, id=acompanhamento_id)
    if request.method == 'POST':
        form = AcompanhamentoForm(request.POST, instance=acompanhamento)
        if form.is_valid():
            form.save()
            return redirect('listar_ingredientes')
    else:
        form = AcompanhamentoForm(instance=acompanhamento)
    return render(request, 'ingrediente/editar_acompanhamento.html', {'form': form})

def remover_acompanhamento(request, acompanhamento_id):
    acompanhamento = get_object_or_404(Acompanhamento, id=acompanhamento_id)
    if request.method == 'POST':
        acompanhamento.delete()
        return redirect('listar_ingredientes')
    return render(request, 'ingrediente/remover_acompanhamento.html', {'acompanhamento': acompanhamento})


# ------------- Sabores -------------
def adicionar_sabor(request):
    if request.method == 'POST':
        form = SaborForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('listar_ingredientes')
    else:
        form = SaborForm()
    return render(request, 'ingrediente/adicionar_sabor.html', {'form': form})

def editar_sabor(request, sabor_id):
    sabor = get_object_or_404(Sabor, id=sabor_id)
    if request.method == 'POST':
        form = SaborForm(request.POST, instance=sabor)
        if form.is_valid():
            form.save()
            return redirect('listar_ingredientes')
    else:
        form = SaborForm(instance=sabor)
    return render(request, 'ingrediente/editar_sabor.html', {'form': form})

def remover_sabor(request, sabor_id):
    sabor = get_object_or_404(Sabor, id=sabor_id)
    if request.method == 'POST':
        sabor.delete()
        return redirect('listar_ingredientes')
    return render(request, 'ingrediente/remover_sabor.html', {'sabor': sabor})


# ------------- Tamanhos -------------
def adicionar_tamanho(request):
    if request.method == 'POST':
        form = TamanhoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('listar_ingredientes')
    else:
        form = TamanhoForm()
    return render(request, 'ingrediente/adicionar_tamanho.html', {'form': form})

def editar_tamanho(request, tamanho_id):
    tamanho = get_object_or_404(Tamanho, id=tamanho_id)
    if request.method == 'POST':
        form = TamanhoForm(request.POST, instance=tamanho)
        if form.is_valid():
            form.save()
            return redirect('listar_ingredientes')
    else:
        form = TamanhoForm(instance=tamanho)
    return render(request, 'ingrediente/editar_tamanho.html', {'form': form})

def remover_tamanho(request, tamanho_id):
    tamanho = get_object_or_404(Tamanho, id=tamanho_id)
    if request.method == 'POST':
        tamanho.delete()
        return redirect('listar_ingredientes')
    return render(request, 'ingrediente/remover_tamanho.html', {'tamanho': tamanho})

templates/ingrediente/adicionar_acompanhamento.html
{% extends 'base.html' %}

{% block title %}Adicionar Acompanhamento{% endblock %}

{% block content %}
<div class="container mt-4">
    <h2 class="mb-4">Adicionar Novo Acompanhamento</h2>

    <form method="POST">
        {% csrf_token %}
        <div class="mb-3">
            <label for="id_nome" class="form-label">Nome</label>
            <input type="text" class="form-control" id="id_nome" name="nome" required>
        </div>
        <div class="mb-3">
            <label for="id_preco_adicional" class="form-label">Preço Adicional</label>
            <input type="number" step="0.01" class="form-control" id="id_preco_adicional" name="preco_adicional" required>
        </div>

        <div class="d-flex justify-content-start mt-4">
            <button type="submit" class="btn btn-primary mr-2">Salvar</button>
            <a href="{% url 'listar_ingredientes' %}" class="btn btn-secondary">Voltar</a>
        </div>
    </form>
</div>
{% endblock %}

templates/ingrediente/adicionar_ingrediente.html
<h1>Adicionar Ingrediente</h1>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Salvar</button>
</form>
<a href="{% url 'listar_ingredientes' %}">Voltar à lista de ingredientes</a>

templates/ingrediente/adicionar_sabor.html
{% extends 'base.html' %}

{% block title %}Adicionar Novo Sabor{% endblock %}

{% block content %}
<div class="container mt-4">
    <h2 class="mb-4">Adicionar Novo Sabor</h2>

    <form method="POST">
        {% csrf_token %}
        <div class="mb-3">
            <label for="id_nome" class="form-label">Nome</label>
            <input type="text" class="form-control" id="id_nome" name="nome" required>
        </div>
        <div class="mb-3">
            <label for="id_preco_adicional" class="form-label">Preço Adicional</label>
            <input type="number" step="0.01" class="form-control" id="id_preco_adicional" name="preco_adicional" required>
        </div>

        <div class="d-flex justify-content-start mt-4">
            <button type="submit" class="btn btn-primary mr-2">Salvar</button>
            <a href="{% url 'listar_ingredientes' %}" class="btn btn-secondary">Voltar</a>
        </div>
    </form>
</div>
{% endblock %}

templates/ingrediente/adicionar_tamanho.html
{% extends 'base.html' %}

{% block title %}Adicionar Novo Tamanho{% endblock %}

{% block content %}
<div class="container mt-4">
    <h1 class="mb-4">Adicionar Novo Tamanho</h1>

    <form method="POST">
        {% csrf_token %}
        <div class="form-group mb-3">
            <label for="id_nome" class="form-label">Nome</label>
            <input type="text" name="nome" id="id_nome" class="form-control" value="{{ form.nome.value|default_if_none:'' }}" required>
        </div>
        <div class="form-group mb-3">
            <label for="id_preco_adicional" class="form-label">Preço Adicional</label>
            <input type="number" step="0.01" name="preco_adicional" id="id_preco_adicional" class="form-control" value="{{ form.preco_adicional.value|default_if_none:'' }}" required>
        </div>
        
        <div class="d-flex justify-content-start mt-4">
            <button type="submit" class="btn btn-primary mr-2">Salvar</button>
            <a href="{% url 'listar_ingredientes' %}" class="btn btn-secondary">Voltar</a>
        </div>
    </form>
</div>
{% endblock %}

templates/ingrediente/editar_acompanhamento.html
{% extends 'base.html' %}

{% block title %}Editar Acompanhamento{% endblock %}

{% block content %}
<div class="container mt-4">
    <h2 class="mb-4">Editar Acompanhamento</h2>

    <form method="POST" class="mb-4">
        {% csrf_token %}
        <div class="form-group mb-3">
            <label for="{{ form.nome.id_for_label }}">{{ form.nome.label }}</label>
            <input type="text" class="form-control" id="{{ form.nome.id_for_label }}" name="{{ form.nome.name }}" value="{{ form.nome.value }}" required>
        </div>
        <div class="form-group mb-3">
            <label for="{{ form.preco_adicional.id_for_label }}">{{ form.preco_adicional.label }}</label>
            <input type="number" step="0.01" class="form-control" id="{{ form.preco_adicional.id_for_label }}" name="{{ form.preco_adicional.name }}" value="{{ form.preco_adicional.value }}" required>
        </div>
        <div class="d-flex justify-content-start mt-4">
            <button type="submit" class="btn btn-primary mr-2">Salvar</button>
            <a href="{% url 'listar_ingredientes' %}" class="btn btn-secondary">Voltar</a>
        </div>
    </form>
</div>
{% endblock %}

templates/ingrediente/editar_ingrediente.html
<h1>Editar Ingrediente</h1>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Salvar Alterações</button>
</form>
<a href="{% url 'listar_ingredientes' %}">Voltar à lista de ingredientes</a>

templates/ingrediente/editar_sabor.html
{% extends 'base.html' %}

{% block title %}Editar Sabor{% endblock %}

{% block content %}
<div class="container mt-4">
    <h2 class="mb-4">Editar Sabor</h2>

    <form method="POST" class="mb-4">
        {% csrf_token %}
        <div class="form-group mb-3">
            <label for="{{ form.nome.id_for_label }}">{{ form.nome.label }}</label>
            <input type="text" class="form-control" id="{{ form.nome.id_for_label }}" name="{{ form.nome.name }}" value="{{ form.nome.value }}" required>
        </div>
        <div class="form-group mb-3">
            <label for="{{ form.preco_adicional.id_for_label }}">{{ form.preco_adicional.label }}</label>
            <input type="number" step="0.01" class="form-control" id="{{ form.preco_adicional.id_for_label }}" name="{{ form.preco_adicional.name }}" value="{{ form.preco_adicional.value }}" required>
        </div>
        <div class="d-flex justify-content-start mt-4">
            <button type="submit" class="btn btn-primary mr-2">Salvar</button>
            <a href="{% url 'listar_ingredientes' %}" class="btn btn-secondary">Voltar</a>
        </div>
    </form>
</div>
{% endblock %}

templates/ingrediente/editar_tamanho.html
{% extends 'base.html' %}

{% block title %}Editar Tamanho{% endblock %}

{% block content %}
<div class="container mt-4">
    <h2 class="mb-4">Editar Tamanho</h2>

    <form method="POST" class="mb-4">
        {% csrf_token %}
        <div class="form-group">
            <label for="{{ form.nome.id_for_label }}">{{ form.nome.label }}</label>
            <input type="text" class="form-control" id="{{ form.nome.id_for_label }}" name="{{ form.nome.name }}" value="{{ form.nome.value }}" required>
        </div>
        <div class="form-group">
            <label for="{{ form.preco_adicional.id_for_label }}">{{ form.preco_adicional.label }}</label>
            <input type="number" step="0.01" class="form-control" id="{{ form.preco_adicional.id_for_label }}" name="{{ form.preco_adicional.name }}" value="{{ form.preco_adicional.value }}" required>
        </div>
        <div class="d-flex justify-content-start mt-4">
            <button type="submit" class="btn btn-primary mr-2">Salvar</button>
            <a href="{% url 'listar_ingredientes' %}" class="btn btn-secondary">Voltar</a>
        </div>
    </form>
</div>
{% endblock %}

templates/ingrediente/listar_ingredientes.html
{% extends 'base.html' %}

{% block title %}Lista de Tamanhos, Sabores e Acompanhamentos{% endblock %}

{% block content %}
<div class="container mt-4">
    <h1 class="mb-4">Lista de Tamanhos</h1>
    <a href="{% url 'adicionar_tamanho' %}" class="btn btn-primary mb-3">Adicionar Tamanho</a>
    <ul class="list-group mb-5">
        {% for tamanho in tamanhos %}
            <li class="list-group-item d-flex justify-content-between align-items-center">
                {{ tamanho.nome }} - R$ {{ tamanho.preco_adicional }}
                <span>
                    <a href="{% url 'editar_tamanho' tamanho.id %}" class="btn btn-warning btn-sm">Editar</a>
                    <a href="{% url 'remover_tamanho' tamanho.id %}" class="btn btn-danger btn-sm ml-2">Remover</a>
                </span>
            </li>
        {% empty %}
            <li class="list-group-item">Nenhum tamanho disponível.</li>
        {% endfor %}
    </ul>

    <h1 class="mb-4">Lista de Sabores</h1>
    <a href="{% url 'adicionar_sabor' %}" class="btn btn-primary mb-3">Adicionar Sabor</a>
    <ul class="list-group mb-5">
        {% for sabor in sabores %}
            <li class="list-group-item d-flex justify-content-between align-items-center">
                {{ sabor.nome }} - R$ {{ sabor.preco_adicional }}
                <span>
                    <a href="{% url 'editar_sabor' sabor.id %}" class="btn btn-warning btn-sm">Editar</a>
                    <a href="{% url 'remover_sabor' sabor.id %}" class="btn btn-danger btn-sm ml-2">Remover</a>
                </span>
            </li>
        {% empty %}
            <li class="list-group-item">Nenhum sabor disponível.</li>
        {% endfor %}
    </ul>

    <h1 class="mb-4">Lista de Acompanhamentos</h1>
    <a href="{% url 'adicionar_acompanhamento' %}" class="btn btn-primary mb-3">Adicionar Acompanhamento</a>
    <ul class="list-group">
        {% for acompanhamento in acompanhamentos %}
            <li class="list-group-item d-flex justify-content-between align-items-center">
                {{ acompanhamento.nome }} - R$ {{ acompanhamento.preco_adicional }}
                <span>
                    <a href="{% url 'editar_acompanhamento' acompanhamento.id %}" class="btn btn-warning btn-sm">Editar</a>
                    <a href="{% url 'remover_acompanhamento' acompanhamento.id %}" class="btn btn-danger btn-sm ml-2">Remover</a>
                </span>
            </li>
        {% empty %}
            <li class="list-group-item">Nenhum acompanhamento disponível.</li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

templates/ingrediente/remover_acompanhamento.html
{% extends 'base.html' %}

{% block title %}Remover Acompanhamento{% endblock %}

{% block content %}
<div class="container mt-4">
    <h2 class="mb-4">Remover Acompanhamento</h2>
    <p class="mb-4">Tem certeza de que deseja remover o acompanhamento <strong>"{{ acompanhamento.nome }}"</strong>?</p>

    <form method="POST" class="mb-4">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Remover</button>
        <a href="{% url 'listar_ingredientes' %}" class="btn btn-secondary ml-2">Cancelar</a>
    </form>
</div>
{% endblock %}

templates/ingrediente/remover_ingrediente.html
<h1>Remover Ingrediente</h1>
<p>Você tem certeza que deseja remover o ingrediente {{ ingrediente.nome }}?</p>
<form method="POST">
    {% csrf_token %}
    <button type="submit">Remover</button>
</form>
<a href="{% url 'listar_ingredientes' %}">Cancelar</a>

templates/ingrediente/remover_sabor.html
<h1>Remover sabor</h1>
<p>Você tem certeza que deseja remover o acompanhamento {{ sabor.nome }}?</p>
<form method="POST">
    {% csrf_token %}
    <button type="submit">Remover</button>
</form>
<a href="{% url 'listar_ingredientes' %}">Cancelar</a>

templates/ingrediente/remover_tamanho.html
{% extends 'base.html' %}

{% block title %}Remover Tamanho{% endblock %}

{% block content %}
<div class="container mt-4">
    <h2 class="mb-4">Remover Tamanho</h2>
    <p class="mb-4">Tem certeza de que deseja remover o tamanho <strong>"{{ tamanho.nome }}"</strong>?</p>

    <form method="POST" class="mb-4">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Remover</button>
        <a href="{% url 'listar_ingredientes' %}" class="btn btn-secondary ml-2">Cancelar</a>
    </form>
</div>
{% endblock %}